#!/usr/bin/env bash
#
# runtime/host/setup.sh — ai-org-os のホスト側セットアップ (Phase 5b-3, Issue #78)
#
# 1 回だけ叩く: ホスト OS 上で Mind が必要とする python 環境を整え、
# spawn-mind.sh / その他のホスト側スクリプトが参照する config.env を生成する。
#
# やること:
#   1. 前提検証 (python3 / claude / pip)
#   2. runtime/host/.venv/ 作成 (既存なら再利用、--recreate で作り直し)
#   3. .venv に mcp をインストール
#   4. OS ネイティブのパス解決 (Windows なら C:/... 形式、Linux/Mac は通常の絶対パス)
#   5. runtime/host/config.env を atomic に書き出す
#       HOST_PYTHON_BIN=...
#       HOST_RUNTIME_DIR=...
#       HOST_NEXUS_PY=...
#       HOST_SETUP_AT=...
#
# やらないこと:
#   - claude code login (ユーザー責任、ADR-0012 §2 責務 3)
#   - ANTHROPIC_API_KEY 設定 (人間が外から渡す、ADR-0016)
#   - Docker / Realm Container の起動 (ADR-0014 §3 D = 人間制御領域)
#
# 関連:
#   - ADR-0014 §3 (Realm 物理境界、ホスト = カテゴリ B)
#   - ADR-0016 (Container = コア / ホスト = Mind の認証経路)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

VENV_DIR="${SCRIPT_DIR}/.venv"
CONFIG_PATH="${SCRIPT_DIR}/config.env"

RECREATE_VENV=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --recreate-venv)
      RECREATE_VENV=1
      shift
      ;;
    -h|--help)
      cat <<HELP
Usage: $0 [--recreate-venv]

Bootstrap host-side prerequisites for ai-org-os Mind processes.

Options:
  --recreate-venv   既存の .venv を削除して作り直す (mcp の major upgrade 等)

After running this, you can:
  - bash runtime/pillars/lifecycle/spawn-mind.sh <kind> <persona> <name>
  - cd runtime/realm && docker compose up -d --build
HELP
      exit 0
      ;;
    *)
      echo "[setup] unknown option: $1" >&2
      exit 1
      ;;
  esac
done

echo "[setup] ai-org-os host setup starting"
echo "[setup]   runtime dir: ${RUNTIME_DIR}"

# ----- 1. 前提検証 -----

if ! command -v python3 >/dev/null 2>&1; then
  echo "[setup][ERROR] python3 not found in PATH." >&2
  echo "[setup][HINT] Install Python 3.10+ first." >&2
  exit 2
fi

PY_VER="$(python3 --version 2>&1 | head -1)"
echo "[setup]   python: ${PY_VER}"

if ! command -v claude >/dev/null 2>&1; then
  echo "[setup][WARN] claude CLI not found in PATH." >&2
  echo "[setup][WARN] Mind processes won't be able to launch until claude is installed and logged in (ADR-0016)." >&2
  echo "[setup][WARN] Continuing anyway; install claude code and re-run when ready." >&2
fi

# ----- 2. venv 作成 -----

if [ "${RECREATE_VENV}" = "1" ] && [ -d "${VENV_DIR}" ]; then
  echo "[setup]   removing existing venv at ${VENV_DIR}"
  rm -rf "${VENV_DIR}"
fi

if [ ! -d "${VENV_DIR}" ]; then
  echo "[setup]   creating venv at ${VENV_DIR}"
  python3 -m venv "${VENV_DIR}"
else
  echo "[setup]   reusing existing venv at ${VENV_DIR}"
fi

# venv の python と pip の実体を OS 別に解決
if [ -x "${VENV_DIR}/Scripts/python.exe" ]; then
  VENV_PY="${VENV_DIR}/Scripts/python.exe"
  VENV_PIP="${VENV_DIR}/Scripts/pip.exe"
elif [ -x "${VENV_DIR}/bin/python" ]; then
  VENV_PY="${VENV_DIR}/bin/python"
  VENV_PIP="${VENV_DIR}/bin/pip"
else
  echo "[setup][ERROR] venv python not found under ${VENV_DIR}" >&2
  exit 3
fi

# ----- 3. mcp install -----

echo "[setup]   installing mcp into venv (quiet)"
# pip 自体の upgrade は意図的にスキップ (Windows の pip self-update 保護で警告が出る、
# mcp の install には影響なし)。
"${VENV_PIP}" install --quiet --disable-pip-version-check "mcp>=1.0"

# mcp が import できることを確認
if ! "${VENV_PY}" -c "import mcp" 2>/dev/null; then
  echo "[setup][ERROR] mcp import failed after install" >&2
  exit 4
fi
echo "[setup]   mcp install ok"

# ----- 4. OS ネイティブのパス解決 -----

# Python の pathlib を使って絶対パスを resolve、Windows 上では C:/... 形式の
# forward-slash で出す。これは claude code on Windows / Linux / Mac いずれも受理する。
HOST_PYTHON_BIN="$("${VENV_PY}" - <<'PY'
from pathlib import Path
import sys
p = Path(sys.executable).resolve()
print(p.as_posix())
PY
)"

HOST_RUNTIME_DIR="$(python3 - "${RUNTIME_DIR}" <<'PY'
from pathlib import Path
import sys
print(Path(sys.argv[1]).resolve().as_posix())
PY
)"

HOST_NEXUS_PY="${HOST_RUNTIME_DIR}/pillars/conduit/nexus.py"

if [ ! -f "${HOST_NEXUS_PY}" ]; then
  echo "[setup][ERROR] nexus.py not found at expected path: ${HOST_NEXUS_PY}" >&2
  exit 5
fi

# ----- 5. config.env を atomic に書き出す -----

SETUP_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
TMP_CONFIG="${CONFIG_PATH}.tmp.$$"

cat > "${TMP_CONFIG}" <<CONFIG
# Generated by runtime/host/setup.sh — do not edit by hand.
# Re-run setup.sh to regenerate. Re-run with --recreate-venv if mcp 等を更新したいとき。
#
# このファイルは .gitignore で除外されており、ホスト固有のため commit しない。

HOST_PYTHON_BIN=${HOST_PYTHON_BIN}
HOST_RUNTIME_DIR=${HOST_RUNTIME_DIR}
HOST_NEXUS_PY=${HOST_NEXUS_PY}
HOST_SETUP_AT=${SETUP_AT}
CONFIG

mv -f "${TMP_CONFIG}" "${CONFIG_PATH}"

echo "[setup] OK. ${CONFIG_PATH} written:"
sed 's/^/[setup]   /' "${CONFIG_PATH}"

echo ""
echo "[setup] Next steps:"
echo "[setup]   1. (任意) export ANTHROPIC_API_KEY=... if you want Judgment Pillar to use real Claude"
echo "[setup]   2. cd runtime/realm && docker compose up -d --build   (Conductor が回り始める)"
echo "[setup]   3. bash runtime/pillars/inbox/submit-issue.sh \"title\" \"body\""
echo "[setup]   4. bash runtime/pillars/lifecycle/spawn-mind.sh generic designer alice"
echo "[setup]   5. cd runtime/minds/alice && claude   (Mind が走り出す)"
